### ISSUE TITLE
Order features within popup by their usage.

### ISSUE THREAD

**Issue by kmcostel** [marklogic/eauser-geomapper#42]
ie. Most commonly used feature listed first, etc. (May not be possible with current data.)

**Comment by dmcassel** [comment]
See orderBy under [creating a facet definition](http://docs.marklogic.com/guide/search-dev/javascript#id_73182).

**Comment by liangdanica** [comment]
It's not possible (or at least for the moment!) to order commonly used features for each user since there is no way to track how much more they use one feature vs. another. However, I was able to order the features and industries by frequency in the left filter "bar." I believe this is now part of my pull request. :)

**Comment by liangdanica** [comment]
Made the count of both features and industries visible. Both features and industries should look something like this:
Earwax _(2)_

**Comment by kmcostel** [comment]
Change from ordering by usage (won't be able to know the usage of features) to alphabetically sorted.
