### ISSUE TITLE
Create user stories for application.

### ISSUE THREAD

**Issue by kmcostel** [marklogic/eauser-geomapper#51]
Ex. Screenshots of various screens representing various states of the application based on some input to the program ie. a mouse click or on page load.

**Comment by kmcostel** [comment]
May be better to leave towards end of project when it is more complete and finalized

**Comment by liangdanica** [comment]
Screenshots sound great. I think Jen was also referring to the overall why/what of each functionality and scenarios in which they would prove to be helpful. Hmm, maybe we can work on user stories after we're done with the most basic version of our map. That way, it will help us prioritize what 'extra' issues we can work on after that! :)

i was looking at some online examples, and it seems like this is a format that many people use:
As a <type of user>, I want <some goal> so that <some reason>.
