### ISSUE TITLE
Create button in formatPopup() that when clicked creates a popup in the browser that shows an editable view of that user's information.

### ISSUE THREAD

**Issue by kmcostel** [marklogic/eauser-geomapper#56]
Button will exist at the bottom of the map popup from #34.

**Comment by graceyin1218** [comment]
The daily update from Marketo will return all users whose entries have changed in the last 24 hrs. If we manually change any of those fields, we can see a discrepancy between the Marketo data and the data stored in MarkLogic, but we won't be able to tell if the difference is because the stuff in MarkLogic is outdated or because we manually updated it...

If we created editable fields that do not match anything Marketo returns, then we could probably avoid this issue.

**Comment by graceyin1218** [comment]
In the meeting with the three Js, people mentioned wanting to be able to take notes on users and manually edit stuff in the geomapper.

Also, Angular really doesn't like the button in the popup... Need to find a workaround 😢

**Comment by kmcostel** [comment]
Deleting, #54 already was made for this
